<Project>
	<PropertyGroup>
		<GameDir>D:\Program Files (x86)\Steam\steamapps\common\A Dance of Fire and Ice</GameDir>
		<GameManagedDir>$(GameDir)\A Dance of Fire and Ice_Data\Managed</GameManagedDir>
		<GameModsDir>$(GameDir)\Mods</GameModsDir>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<PlatformTarget>x64</PlatformTarget>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
	</PropertyGroup>
</Project>
